backend:
  name: github
  repo: ttola/megakad
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
